[my_switches]
# Masukkan IP atau Hostname perangkat Anda
Switch-Utama ansible_host=192.168.1.10
Switch-Lantai2 ansible_host=192.168.1.11

[my_switches:vars]
# Informasi Login
ansible_user=admin
ansible_password=password_anda
# Koneksi khusus network
ansible_connection=network_cli
ansible_network_os=cisco.ios.ios
# Jika butuh password 'enable'
ansible_become=yes
ansible_become_method=enable
ansible_become_password=password_enable_anda
